version: "3.7"
services:
  app:
    build:
      args:
        user: ${SYS_USER}
        uid: ${SYS_UID}
      context: ./docker/app
    container_name: ${CONTAINERS_PREFIX}-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - db
  db:
    image: postgres:12.3-alpine
    container_name: ${CONTAINERS_PREFIX}-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
  web:
    image: nginx:1.17.9-alpine
    container_name: ${CONTAINERS_PREFIX}-web
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/var/www
      - ./docker/web/:/etc/nginx/conf.d
    depends_on:
      - db
      - app
